// Generated by CoffeeScript 1.7.1
"use strict";
var config, container, database, express, flash, monolog, passport, path, pimple, routes, swig, util;

express = require('express');

pimple = require('pimple');

swig = require('swig');

monolog = require('monolog');

util = require('util');

database = require('./lib/database');

routes = require('./lib/routes');

path = require('path');

passport = require('passport');

flash = require('connect-flash');

config = require('./lib/config');

container = pimple({
  port: process.env.PORT || 3000,
  youtub_api_key: process.env.EXPRESS_VIDEO_YOUTUBE_API_KEY,
  connection_string: process.env.EXPRESS_VIDEO_MONGODB_CONNECTION_STRING,
  debug: process.env.NODE_ENV === "production" ? false : true
});

container.set("app", container.share(function() {
  var app;
  app = express();
  app.configure(function() {
    var renderFile;
    app.engine('html', renderFile = container.swig.renderFile);
    app.engine('twig', renderFile);
    app.set('view engine', 'html');
    app.locals(container.locals);
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express["static"](path.join(__dirname, "..", "public")));
    app.use(express.favicon());
    return app.disable("verbose errors");
  });
  app.configure('development', function() {
    app.use(express.logger("dev"));
    app.use(container.monolog.middleware());
    app.use(express.session({
      secret: config.session_secret
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(flash());
    return app.enable('verbose errors');
  });
  app.configure('testing', function() {
    return container.set('connection_string', process.env.EXPRESS_VIDEO_MONGODB_CONNECTION_STRING_TEST);
  });

  /*
  route map mixin
  mount routes with a single object
  @param routes
  @param prefix
   */
  app.map = function(routes, prefix) {
    var key, value;
    if (prefix == null) {
      prefix = "";
    }
    for (key in routes) {
      value = routes[key];
      switch (typeof value) {
        case "object":
          if (value instanceof Array) {
            value.unshift(prefix);
            this[key].apply(this, value);
          } else {
            this.map(value, prefix + key);
          }
          break;
        case "function":
          this[key].apply(this, [prefix, value]);
      }
    }
    return this;
  };

  /*
      basic caching
   */
  app.use(function(req, res, next) {
    if (req.method === "GET") {
      res.header('Cache-Control', "max-age=" + 120);
      res.header('X-Powered-By', 'mparaiso mparaiso@online.fr');
    }
    return next();
  });
  app.map(container.routes);

  /* 
      error handlers 
      @see https://github.com/visionmedia/express/blob/master/examples/error-pages/index.js
   */
  app.use(function(req, res, next) {
    res.status(404);
    return res.render('404', {
      code: res.statusCode
    });
  });
  app.use(function(err, req, res, next) {
    app.get('monolog').error(err);
    res.status(err.status || 500);
    return res.render('500');
  });
  return app;
})).set("locals", container.share(function() {
  return {
    title: "mpm.video",
    paginate: function(array, length, start) {
      var divisions, _i, _results;
      if (start == null) {
        start = 0;
      }
      divisions = Math.ceil(array.length / length);
      return (function() {
        _results = [];
        for (var _i = start; start <= divisions ? _i < divisions : _i > divisions; start <= divisions ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).map(function(i) {
        return array.slice(i * length, i * length + length);
      });
    }
  };
})).set("swig", container.share(function() {
  swig.setDefaults({
    cache: 'memory'
  });
  return swig;
})).set("routes", container.share(function() {
  return routes;
})).set("db", container.share(function() {
  database.set("debug", container.debug);
  return database;
})).set("User", container.share(function() {
  return container.db.model('User');
})).set("Video", container.share(function() {
  return container.db.model('Video');
})).set("Playlist", container.share(function() {
  return container.db.model('Playlist');
})).set("monolog", container.share(function() {
  var logger;
  logger = new monolog.Logger("express logger");
  logger.addHandler(new monolog.handler.StreamHandler(__dirname + "/../temp/log.txt"));
  logger.middleware = function(message) {
    var init;
    if (message == null) {
      message = "debug";
    }
    init = false;
    return function(req, res, next) {
      if (!init) {
        logger.addProcessor(new monolog.processor.ExpressProcessor(req.app));
        req.app.set('monolog', logger);
        init = true;
      }
      logger.debug("" + message + " " + req.method + " " + req.path);
      return next();
    };
  };
  return logger;
}));

module.exports = container;

//# sourceMappingURL=container.map
