// Generated by CoffeeScript 1.7.1

/*
    Copyright © 2014 mparaiso <mparaiso@online.fr>. All Rights Reserved.
 */
module.exports = function(container) {
  return container.set('middlewares', container.share(function(c) {
    var middlewares, q, _;
    q = c.q;
    _ = c._;

    /* 
     * MIDDLEWARES 
     * @namespace
     */
    middlewares = {};
    middlewares.video = function(req, res, next, id) {
      return c.Video.findOneById(id).then(function(video) {
        var err;
        if (!video) {
          err = new Error('Video not found');
          err.status = 404;
          return err;
        } else {
          res.locals.video = video;
          return next();
        }
      })["catch"](next);
    };
    middlewares.playlist = function(req, res, next, id) {
      return c.Playlist.findById(id).where({
        "private": false
      }).populate('videos owner').exec(function(err, playlist) {
        if (err) {
          err.status = 500;
          return next(err);
        } else if (!playlist) {
          err = new Error("Playlist with id " + id + " not found");
          err.status = 404;
          return next(err);
        } else {
          res.locals.playlist = playlist;
          return next();
        }
      });
    };
    middlewares.categories = (function(req, res, next) {
      return c.Category.whereVideoExist().then(function(categories) {
        res.locals.categories = categories;
        return next();
      }, next);
    });
    middlewares.belongsToUser = function(model, param) {
      return function(req, res, next) {
        return model.findOne({
          _id: res.locals[param].id,
          owner: req.user.id
        }).exec(function(err, res) {
          if (err) {
            err.status = 403;
            return next(err);
          } else if (!res) {
            err = new Error("Access to resource " + param + " for " + req.user + " forbidden");
            return next(err);
          } else {
            return next();
          }
        });
      };
    };
    middlewares.cache = function(req, res, next) {
      if (req.method === "GET" && req.app.get('env') === "production") {
        res.header('Cache-Control', "max-age=" + (1000 * 60));
        res.header('X-Powered-By', 'mparaiso mparaiso@online.fr');
      }
      return next();
    };

    /*
     * @TODO rethink apis
    middlewares.videoApi = do ->
        controller = new Rest.Controller(c.express(),{allow:['list','get']})
        controller.setAdapter(new Rest.adapter.MongooseAdapter(c.Video))
        controller.handle()
    
    middlewares.playlistApi = do ->
        controller = new Rest.Controller(c.express(),{allow:['list','get']})
        controller.setAdapter(new Rest.adapter.MongooseAdapter(c.Playlist))
        controller.handle()
     */

    /*
    error handlers
    @see https://github.com/visionmedia/express/blob/master/examples/error-pages/index.js
     */
    middlewares.error = function(err, req, res, next) {
      c.logger.error(err);
      switch (err.status) {
        case 404:
          res.status(404);
          return res.render('404');
        default:
          res.status(500);
          return res.render('500');
      }
    };
    middlewares.requestLogger = function(req, res, next) {
      res.once('finish', function() {
        var message;
        message = {
          request: _.pick(req, ['headers', 'trailers', 'method', 'url', 'statusCode', 'ip', 'port', 'user', 'error', "err", 'cookies', 'session']),
          response: _.pick(res, ['statusCode', 'trailers', 'headers', 'error', "err"])
        };
        if (res.statusCode >= 400) {
          return container.logger.error(message);
        } else {
          return container.logger.info(message);
        }
      });
      return next();
    };
    middlewares.firewall = function(req, res, next) {
      var path;
      path = (req.app._router.match(req.method, req.originalUrl) || {}).path;
      return c.acl.query(req.isAuthenticated() && req.user, c.resources.ROUTE, path, function(err, isAllowed) {
        if (isAllowed === true) {
          return next();
        } else if (!req.isAuthenticated()) {
          return res.redirect('/login');
        } else {
          return next(err || (path && c.errors.Forbidden("Forbidden : User '" + req.user + "' with role '" + req.user.role + "' tried to access " + req.originalUrl)) || c.errors.NotFound("url " + req.originalUrl + " not found "));
        }
      });
    };
    return middlewares;
  }));
};

//# sourceMappingURL=middlewares.map
