// Generated by CoffeeScript 1.7.1

/*
    Copyright © 2014 mparaiso <mparaiso@online.fr>. All Rights Reserved.
 */
var mixins;

mixins = exports;


/*
    route map mixin
    mount routes with a single object
    @param routes
    @param prefix
 */

mixins.map = function(routes, prefix) {
  var key, value;
  if (prefix == null) {
    prefix = "";
  }
  for (key in routes) {
    value = routes[key];
    switch (typeof value) {
      case "object":
        if (value instanceof Array) {
          value.unshift(prefix);
          this[key].apply(this, value);
        } else {
          this.map(value, prefix + key);
        }
        break;
      default:
        this[key].apply(this, [prefix, value]);
    }
  }
  return this;
};


/*
helper function for app.param
register multiple param at the same time
@param {Array.<{name:String,callback:Function}>} params an map of params
 */

mixins.params = function(params) {
  var param, _i, _len;
  if (params == null) {
    params = {};
  }
  for (_i = 0, _len = params.length; _i < _len; _i++) {
    param = params[_i];
    this.param(param.name, param.callback);
  }
  return this;
};

//# sourceMappingURL=mixins.map
