// Generated by CoffeeScript 1.7.1
"use strict";
var config, util;

util = require('util');


/*
	PRODUCTION
 */

config = {
  connection_string: process.env.EXPRESS_VIDEO_MONGODB_CONNECTION_STRING,
  youtube_apikey: process.env.EXPRESS_VIDEO_YOUTUBE_API_KEY,
  port: process.env.PORT,
  mongoose_debug: false,
  session_secret: process.env.SESSION_SECRET
};


/*
	STAGING
 */

if (process.env.NODE_ENV === "staging") {
  util._extend(config, {});
}


/*
	DEVELOPMENT
 */

if (process.env.NODE_ENV === "development") {
  util._extend(config, {});
}


/* 
	TESTING
 */

if (process.env.NODE_ENV === "testing") {
  util._extend(config, {
    connection_string: process.env.EXPRESS_VIDEO_MONGODB_CONNECTION_STRING_TEST
  });
}

module.exports = config;

//# sourceMappingURL=config.map
