// Generated by CoffeeScript 1.7.1
"use strict";
var Playlist, Rest, Video, database, express, forms, middlewares, q;

forms = require('./forms');

Rest = require('mpm.express.rest');

express = require('express');

database = require('./database');

Video = database.model('Video');

Playlist = database.model('Playlist');

q = require('q');


/* 
 * MIDDLEWARES 
 * @namespace
 */

middlewares = {};


/*
    Makes the csrf token mandatory
    add _csrf to res.locals and headers
 */

middlewares.csrf = function(req, res, next) {
  return (express.csrf())(req, res, function(err) {
    if (err) {
      return next(err);
    } else {
      res.locals._csrf = req.csrfToken();
      res.set('_csrf', res.locals._csrf);
      return next();
    }
  });
};

middlewares.video = function(req, res, next, id) {
  return Video.findById(id).select('title private description duration thumbnail owner publishedAt originalId category categoryId').populate('owner category').exec(function(err, video) {
    if (err) {
      err.status = 500;
      return next(err);
    } else if (!video) {
      err = new Error('Video not found');
      err.status = 404;
      return next(err);
    } else {
      res.locals.video = video;
      return next();
    }
  });
};

middlewares.playlist = function(req, res, next, id) {
  return Playlist.findById(id).where({
    "private": false
  }).populate('videos owner').exec(function(err, playlist) {
    if (err) {
      err.status = 500;
      return next(err);
    } else if (!playlist) {
      err = new Error("Playlist with id " + id + " not found");
      err.status = 404;
      return next(err);
    } else {
      res.locals.playlist = playlist;
      return next();
    }
  });
};

middlewares.categories = (function(req, res, next) {
  return res.locals.container.Category.whereVideoExist().then(function(categories) {
    res.locals.categories = categories;
    return next();
  }, next);
});

middlewares.belongsToUser = function(model, param) {
  return function(req, res, next) {
    return model.findOne({
      _id: res.locals[param].id,
      owner: req.user.id
    }).exec(function(err, res) {
      if (err) {
        err.status = 403;
        return next(err);
      } else if (!res) {
        err = new Error("Access to resource " + param + " for " + req.user + " forbidden");
        return next(err);
      } else {
        return next();
      }
    });
  };
};

middlewares.user = function(req, res, next) {
  res.locals.user = req.user;
  return next();
};

middlewares.isLoggedIn = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    return res.redirect('/login');
  }
};

middlewares.cache = function(req, res, next) {
  if (req.method === "GET" && req.app.get('env') === "production") {
    res.header('Cache-Control', "max-age=" + 5);
    res.header('X-Powered-By', 'mparaiso mparaiso@online.fr');
  }
  return next();
};

middlewares.flash = function(req, res, next) {
  res.locals.flash = req.flash();
  return next();
};

middlewares.videoApi = (function() {
  var controller;
  controller = new Rest.Controller(express(), {
    allow: ['list', 'get']
  });
  controller.setAdapter(new Rest.adapter.MongooseAdapter(Video));
  return controller.handle();
})();

middlewares.playlistApi = (function() {
  var controller;
  controller = new Rest.Controller(express(), {
    allow: ['list', 'get']
  });
  controller.setAdapter(new Rest.adapter.MongooseAdapter(Playlist));
  return controller.handle();
})();


/*
error handlers
@see https://github.com/visionmedia/express/blob/master/examples/error-pages/index.js
 */

middlewares.error = function(err, req, res, next) {
  console.error(err);
  switch (String(err.status)) {
    case '404':
      return res.render('404');
    default:
      return res.render('500');
  }
};

module.exports = middlewares;

//# sourceMappingURL=middlewares.map
