// Generated by CoffeeScript 1.7.1
var not_implemented_here, players, util, _;

util = require('util');

_ = require("underscore");

players = exports;

not_implemented_here = function() {
  throw "not implemented here!";
};


/*
	helps render video players
 */

players.Base = (function() {
  function Base() {}

  Base.prototype.canRenderUrl = function(url) {
    return not_implemented_here();
  };

  Base.prototype.toJSON = function() {
    return not_implemented_here();
  };

  Base.prototype.render = function() {
    return not_implemented_here();
  };

  return Base;

})();

players.Youtube = (function() {
  Youtube.prototype.defaultOptions = {
    allowfullscreen: "true",
    width: 640,
    height: 480,
    frameborder: 0
  };

  function Youtube(video_id, options) {
    this.video_id = video_id;
    this.options = options != null ? options : {};
    this.options = _.extend({}, this.defaultOptions, this.options);
    this.src = "//www.youtube.com/embed/" + this.video_id;
  }

  Youtube.prototype.toJSON = function() {
    return {
      src: this.src,
      width: this.options.width,
      height: this.options.height,
      frameborder: this.options.frameborder,
      allowfullscreen: this.options.allowfullscreen
    };
  };

  Youtube.prototype.toHTML = function() {
    var data;
    data = this.toJSON();
    return "<iframe width=\"" + data.width + "\" height=\"" + data.height + "\" src=\"" + data.src + "\" frameborder=\"{data.frameborder}\" " + (data.allowfullscreen ? "allowfullscreen" : void 0) + "></iframe>";
  };

  Youtube.prototype.canRenderUrl = function() {
    return true;
  };

  return Youtube;

})();

//# sourceMappingURL=players.map
